<header class="header">
    <div class="header__logo-box">
        <img class="header__logo" src="images/logo.png" alt="Logo"/>
    </div>
    <nav>
        <ul>
            <li>
                <a href="index.php">Home</a>
            </li>
            <li>
                <a href="product.php">Products</a>
            </li>
            <li>
                <a href="enquire.php">Enquire</a>
            </li>
            <li>
                <a href="manager.php">Manager</a>
            </li>
            <li>
                <a href="enhancements2.php">Enhancements</a>
            </li>
            <li>
                <a href="about.php">About</a>
            </li>
        </ul>
    </nav>
</header>